# Generated by Django 3.1.6 on 2021-03-13 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Admin', '0003_auto_20210313_1954'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='image2',
            field=models.ImageField(upload_to='media/'),
        ),
        migrations.AlterField(
            model_name='products',
            name='image3',
            field=models.ImageField(upload_to='media/'),
        ),
    ]
