# Generated by Django 3.1.6 on 2021-03-30 12:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_myuser_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='myuser',
            old_name='image',
            new_name='image1',
        ),
    ]
