# Generated by Django 3.1.7 on 2021-04-06 01:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0018_auto_20210402_1723'),
    ]

    operations = [
        migrations.AddField(
            model_name='myuser',
            name='coupon_code',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
