# Generated by Django 3.1.7 on 2021-04-09 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0022_referal'),
    ]

    operations = [
        migrations.AlterField(
            model_name='referal',
            name='referal_code',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
